wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 0.975424
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[[[[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0.\
    \ ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0.\
    \ 0.]\n    [0. 0. 0. ... 0. 0. 0.]]\n\n   [[0. 0. 0. ... 0. 0. 0.]\n    [0. 0.\
    \ 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0.\
    \ 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]\n\n   [[0.\
    \ 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n\
    \    ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0.\
    \ 0. ... 0. 0. 0.]]]\n\n\n  [[[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0.\
    \ 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n   \
    \ [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]\n\n   [[0. 0. 0. ... 0.\
    \ 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n\
    \    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0.\
    \ 0. 0.]]\n\n   [[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0.\
    \ 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ...\
    \ 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]]\n\n\n  [[[0. 0. 0. ... 0. 0. 0.]\n\
    \    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0.\
    \ 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]\n\
    \n   [[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ...\
    \ 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n\
    \    [0. 0. 0. ... 0. 0. 0.]]\n\n   [[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ...\
    \ 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n\
    \    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]]\n\n\n  [[[0. 0. 0.\
    \ ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n  \
    \  ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0.\
    \ ... 0. 0. 0.]]\n\n   [[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n\
    \    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0.\
    \ 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]\n\n   [[0. 0. 0. ... 0. 0. 0.]\n\
    \    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0.\
    \ 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]]]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x000001DDA8E01B08>
_n_updates:
  desc: null
  value: 30
_num_timesteps_at_start:
  desc: null
  value: 26734
_total_timesteps:
  desc: null
  value: 1026734
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    code_path: code/ROAR_gym/e2eModel.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1652045053
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 5
      - 13
      - 14
      - 16
      - 22
      - 34
      4: 3.7.12
      5: 0.12.16
      8:
      - 3
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Box([-2.5 -5.   1.  -2.5 -5.   1.  -2.5 -5.   1.  -2.5 -5.   1. ], [-0.5  5.   3.  -0.5  5.   3.  -0.5  5.   3.  -0.5  5.   3.
    ], (12,), float32)
algo:
  desc: null
  value: PPO
batch_size:
  desc: null
  value: 64
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x000001DD9A47DB88>
clip_range_vf:
  desc: null
  value: None
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: 0
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001DD9A492448>
env_name:
  desc: null
  value: roar-e2e-ppo-v0
ep_info_buffer:
  desc: null
  value: 'deque([{''r'': -324.75, ''l'': 34, ''t'': 9849.35105}, {''r'': -324.75,
    ''l'': 34, ''t'': 9864.26471}, {''r'': -376.5, ''l'': 50, ''t'': 9885.201627},
    {''r'': -310.75, ''l'': 31, ''t'': 9900.100886}, {''r'': -298.5, ''l'': 27, ''t'':
    9923.352931}, {''r'': -363.25, ''l'': 46, ''t'': 9943.72209}, {''r'': -299.25,
    ''l'': 26, ''t'': 9954.96865}, {''r'': -432.5, ''l'': 68, ''t'': 9993.880664},
    {''r'': -310.5, ''l'': 30, ''t'': 10018.489376}, {''r'': -298.5, ''l'': 27, ''t'':
    10032.099025}, {''r'': -314.75, ''l'': 32, ''t'': 10048.017256}, {''r'': -283.25,
    ''l'': 22, ''t'': 10069.117618}, {''r'': -304.25, ''l'': 27, ''t'': 10080.927275},
    {''r'': -386.0, ''l'': 54, ''t'': 10105.126014}, {''r'': -337.25, ''l'': 39, ''t'':
    10135.167925}, {''r'': -333.75, ''l'': 37, ''t'': 10151.36489}, {''r'': -169.75,
    ''l'': 49, ''t'': 10174.587764}, {''r'': -296.5, ''l'': 26, ''t'': 10197.166856},
    {''r'': -290.25, ''l'': 24, ''t'': 10209.177954}, {''r'': -137.0, ''l'': 38, ''t'':
    10238.17165}, {''r'': -177.5, ''l'': 50, ''t'': 10270.798322}, {''r'': -343.25,
    ''l'': 41, ''t'': 10290.474057}, {''r'': -295.25, ''l'': 25, ''t'': 10313.146175},
    {''r'': -344.25, ''l'': 41, ''t'': 10332.265778}, {''r'': -390.0, ''l'': 55, ''t'':
    10367.530873}, {''r'': -363.5, ''l'': 47, ''t'': 10388.629871}, {''r'': -395.0,
    ''l'': 57, ''t'': 10414.330367}, {''r'': -333.75, ''l'': 37, ''t'': 10430.850966},
    {''r'': -315.5, ''l'': 31, ''t'': 10444.540368}, {''r'': -401.0, ''l'': 58, ''t'':
    10471.02337}, {''r'': -322.75, ''l'': 34, ''t'': 10498.215697}, {''r'': -482.5,
    ''l'': 84, ''t'': 10534.188313}, {''r'': -286.25, ''l'': 23, ''t'': 10555.749214},
    {''r'': -331.75, ''l'': 36, ''t'': 10571.192855}, {''r'': -319.5, ''l'': 32, ''t'':
    10584.757425}, {''r'': -390.0, ''l'': 55, ''t'': 10610.140574}, {''r'': -366.5,
    ''l'': 48, ''t'': 10631.289285}, {''r'': -397.75, ''l'': 56, ''t'': 10654.859518},
    {''r'': -348.0, ''l'': 41, ''t'': 10672.110465}, {''r'': -190.0, ''l'': 55, ''t'':
    10697.560751}, {''r'': -120.5, ''l'': 32, ''t'': 10711.689576}, {''r'': -572.5,
    ''l'': 114, ''t'': 10759.847925}, {''r'': -291.5, ''l'': 25, ''t'': 10773.174466},
    {''r'': -363.0, ''l'': 45, ''t'': 10792.095654}, {''r'': -331.75, ''l'': 36, ''t'':
    10807.642294}, {''r'': -369.25, ''l'': 47, ''t'': 10828.019059}, {''r'': -322.75,
    ''l'': 34, ''t'': 10843.229037}, {''r'': -331.0, ''l'': 37, ''t'': 10860.23096},
    {''r'': -370.25, ''l'': 48, ''t'': 10879.963797}, {''r'': -540.75, ''l'': 92,
    ''t'': 11038.641896}, {''r'': -282.25, ''l'': 22, ''t'': 11060.656291}, {''r'':
    -235.0, ''l'': 70, ''t'': 11094.061199}, {''r'': -312.75, ''l'': 31, ''t'': 11109.17445},
    {''r'': -318.5, ''l'': 32, ''t'': 11123.611066}, {''r'': -386.75, ''l'': 54, ''t'':
    11147.329949}, {''r'': -334.75, ''l'': 37, ''t'': 11164.401385}, {''r'': -375.75,
    ''l'': 51, ''t'': 11188.262074}, {''r'': -300.5, ''l'': 27, ''t'': 11202.620657},
    {''r'': -308.75, ''l'': 30, ''t'': 11227.887289}, {''r'': -418.5, ''l'': 64, ''t'':
    11267.41999}, {''r'': -331.75, ''l'': 36, ''t'': 11283.339503}, {''r'': -296.75,
    ''l'': 27, ''t'': 11300.222706}, {''r'': -327.75, ''l'': 35, ''t'': 11316.43551},
    {''r'': -366.5, ''l'': 48, ''t'': 11339.471117}, {''r'': -345.5, ''l'': 42, ''t'':
    11362.409127}, {''r'': -278.25, ''l'': 21, ''t'': 11374.612651}, {''r'': -349.0,
    ''l'': 41, ''t'': 11394.974699}, {''r'': -310.5, ''l'': 30, ''t'': 11409.657035},
    {''r'': -360.5, ''l'': 46, ''t'': 11432.703973}, {''r'': -283.25, ''l'': 22, ''t'':
    11454.594573}, {''r'': -336.75, ''l'': 37, ''t'': 11470.479259}, {''r'': -305.5,
    ''l'': 29, ''t'': 11484.409427}, {''r'': -361.0, ''l'': 44, ''t'': 11503.801437},
    {''r'': -437.75, ''l'': 70, ''t'': 11535.87376}, {''r'': -300.25, ''l'': 26, ''t'':
    11549.605397}, {''r'': -520.0, ''l'': 95, ''t'': 11592.432632}, {''r'': -88.25,
    ''l'': 23, ''t'': 11604.666058}, {''r'': -92.25, ''l'': 24, ''t'': 11615.926957},
    {''r'': -358.5, ''l'': 46, ''t'': 11638.825086}, {''r'': -392.75, ''l'': 55, ''t'':
    11664.765198}, {''r'': -322.5, ''l'': 33, ''t'': 11679.759204}, {''r'': -292.5,
    ''l'': 25, ''t'': 11693.637636}, {''r'': -411.75, ''l'': 64, ''t'': 11726.658595},
    {''r'': -294.25, ''l'': 25, ''t'': 11738.459717}, {''r'': -413.25, ''l'': 62,
    ''t'': 11767.382989}, {''r'': -324.75, ''l'': 34, ''t'': 11783.757404}, {''r'':
    -356.25, ''l'': 44, ''t'': 11805.106906}, {''r'': -439.75, ''l'': 71, ''t'': 11848.132303},
    {''r'': -324.0, ''l'': 35, ''t'': 11867.220104}, {''r'': -306.25, ''l'': 28, ''t'':
    11880.282773}, {''r'': -337.75, ''l'': 38, ''t'': 11897.710099}, {''r'': -362.25,
    ''l'': 46, ''t'': 11918.630165}, {''r'': -298.25, ''l'': 26, ''t'': 11931.409804},
    {''r'': -317.0, ''l'': 33, ''t'': 11949.993786}, {''r'': -300.5, ''l'': 27, ''t'':
    11964.27121}, {''r'': -392.75, ''l'': 55, ''t'': 11999.753812}, {''r'': -120.5,
    ''l'': 32, ''t'': 12014.958745}, {''r'': -374.5, ''l'': 50, ''t'': 12039.122006},
    {''r'': -336.75, ''l'': 37, ''t'': 12057.564343}, {''r'': -222.25, ''l'': 64,
    ''t'': 12087.685822}], maxlen=100)'
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 1.0e-05
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x000001DD9A47DD38>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 1
n_epochs:
  desc: null
  value: 10
n_steps:
  desc: null
  value: 8192
normalize_advantage:
  desc: null
  value: 'True'
num_timesteps:
  desc: null
  value: 26734
observation_space:
  desc: null
  value: "Box([[[[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10.\
    \ -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]]\n\n  [[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10.\
    \ -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n \
    \  [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]]\n\n  [[-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   ...\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]\n   [-10. -10. -10. ... -10. -10. -10.]]]\n\n\n [[[-10. -10. -10. ...\
    \ -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]\n   ...\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10.\
    \ -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]]\n\n \
    \ [[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]]\n\n  [[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10.\
    \ -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]]]\n\n\n [[[-10. -10. -10. ... -10. -10. -10.]\n   [-10.\
    \ -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]]\n\n  [[-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   ...\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]\n   [-10. -10. -10. ... -10. -10. -10.]]\n\n  [[-10. -10. -10. ... -10.\
    \ -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10.\
    \ -10. -10.]\n   ...\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]]]\n\n\n [[[-10.\
    \ -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10.\
    \ -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]]\n\
    \n  [[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]]\n\n  [[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10.\
    \ -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]]]], [[[[1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1. 1. 1. ... 1. 1. 1.]\n \
    \  [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ...\
    \ 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1.\
    \ 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]]]\n\n\n [[[1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1. 1. 1. ... 1. 1. 1.]\n \
    \  [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ...\
    \ 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1.\
    \ 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]]]\n\n\n [[[1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1. 1. 1. ... 1. 1. 1.]\n \
    \  [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ...\
    \ 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1.\
    \ 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]]]\n\n\n [[[1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1. 1. 1. ... 1. 1. 1.]\n \
    \  [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ...\
    \ 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1.\
    \ 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]]]], (4, 3, 84, 84), float32)"
policy:
  desc: null
  value: "ActorCriticCnnPolicy(\n  (features_extractor): Atari_PPO_Adapted_CNN(\n\
    \    (network): Sequential(\n      (0): Conv2d(12, 32, kernel_size=(8, 8), stride=(4,\
    \ 4))\n      (1): ReLU()\n      (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2,\
    \ 2))\n      (3): ReLU()\n      (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1,\
    \ 1))\n      (5): ReLU()\n      (6): Flatten(start_dim=1, end_dim=-1)\n      (7):\
    \ Linear(in_features=3136, out_features=256, bias=True)\n    )\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (shared_net): Sequential()\n    (policy_net): Sequential(\n\
    \      (0): Linear(in_features=256, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n    (value_net): Sequential(\n      (0): Linear(in_features=256, out_features=64,\
    \ bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (3): Tanh()\n    )\n  )\n  (action_net): Linear(in_features=64,\
    \ out_features=12, bias=True)\n  (value_net): Linear(in_features=64, out_features=1,\
    \ bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticCnnPolicy'>
policy_kwargs:
  desc: null
  value: '{''features_extractor_class'': <class ''ppo_util.Atari_PPO_Adapted_CNN''>,
    ''features_extractor_kwargs'': {''features_dim'': 256}}'
policy_type:
  desc: null
  value: CnnPolicy
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001DD9A4ED188>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 1
start_time:
  desc: null
  value: 1652044199.6311462
target_kl:
  desc: null
  value: None
tensorboard_log:
  desc: null
  value: runs/ROAR3
training_kwargs:
  desc: null
  value:
    batch_size: 64
    device: cpu
    ent_coef: 0.0
    gamma: 0.99
    learning_rate: 1.0e-05
    n_steps: 8192
    seed: 1
    verbose: 1
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
vf_coef:
  desc: null
  value: 0.5
