wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 0.9589032354746861
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[[[[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0.\
    \ ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0.\
    \ 0.]\n    [0. 0. 0. ... 0. 0. 0.]]\n\n   [[0. 0. 0. ... 0. 0. 0.]\n    [0. 0.\
    \ 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0.\
    \ 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]\n\n   [[0.\
    \ 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n\
    \    ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0.\
    \ 0. ... 0. 0. 0.]]]\n\n\n  [[[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0.\
    \ 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n   \
    \ [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]\n\n   [[0. 0. 0. ... 0.\
    \ 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n\
    \    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0.\
    \ 0. 0.]]\n\n   [[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0.\
    \ 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ...\
    \ 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]]\n\n\n  [[[0. 0. 0. ... 0. 0. 0.]\n\
    \    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0.\
    \ 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]\n\
    \n   [[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ...\
    \ 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n\
    \    [0. 0. 0. ... 0. 0. 0.]]\n\n   [[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ...\
    \ 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n\
    \    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]]\n\n\n  [[[0. 0. 0.\
    \ ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n  \
    \  ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0.\
    \ ... 0. 0. 0.]]\n\n   [[0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n\
    \    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0.\
    \ 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]\n\n   [[0. 0. 0. ... 0. 0. 0.]\n\
    \    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    ...\n    [0. 0.\
    \ 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]\n    [0. 0. 0. ... 0. 0. 0.]]]]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x00000218B0B49F88>
_n_updates:
  desc: null
  value: 30
_num_timesteps_at_start:
  desc: null
  value: 50674
_total_timesteps:
  desc: null
  value: 1050674
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    code_path: code/ROAR_gym/e2eModel.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1651992594
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 1
      - 5
      - 13
      - 14
      - 16
      - 22
      - 34
      4: 3.7.12
      5: 0.12.16
      8:
      - 3
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Box([-2.5 -5.   1.  -2.5 -5.   1.  -2.5 -5.   1.  -2.5 -5.   1. ], [-0.5  5.   3.  -0.5  5.   3.  -0.5  5.   3.  -0.5  5.   3.
    ], (12,), float32)
algo:
  desc: null
  value: PPO
batch_size:
  desc: null
  value: 64
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x00000218A21BCAF8>
clip_range_vf:
  desc: null
  value: None
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: 0.0
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x00000218A1FEBF88>
env_name:
  desc: null
  value: roar-e2e-ppo-v0
ep_info_buffer:
  desc: null
  value: 'deque([{''r'': -636.75, ''l'': 120, ''t'': 1803.904019}, {''r'': -608.5,
    ''l'': 112, ''t'': 1831.80388}, {''r'': -434.75, ''l'': 62, ''t'': 1847.439325},
    {''r'': -467.25, ''l'': 72, ''t'': 1866.239563}, {''r'': -556.0, ''l'': 97, ''t'':
    1890.25321}, {''r'': -455.0, ''l'': 68, ''t'': 1907.340663}, {''r'': -399.5, ''l'':
    52, ''t'': 1920.262269}, {''r'': -452.0, ''l'': 67, ''t'': 1937.716223}, {''r'':
    -523.75, ''l'': 88, ''t'': 1959.808327}, {''r'': -459.0, ''l'': 69, ''t'': 1977.376446},
    {''r'': -561.0, ''l'': 98, ''t'': 2001.784662}, {''r'': -788.25, ''l'': 163, ''t'':
    2041.428111}, {''r'': -432.0, ''l'': 62, ''t'': 2057.913264}, {''r'': -419.75,
    ''l'': 58, ''t'': 2152.14613}, {''r'': -456.0, ''l'': 68, ''t'': 2169.175478},
    {''r'': -723.5, ''l'': 144, ''t'': 2205.851171}, {''r'': -439.0, ''l'': 64, ''t'':
    2221.79651}, {''r'': -521.5, ''l'': 86, ''t'': 2242.801495}, {''r'': -525.75,
    ''l'': 88, ''t'': 2264.863009}, {''r'': -289.25, ''l'': 77, ''t'': 2283.831049},
    {''r'': -378.25, ''l'': 103, ''t'': 2310.434461}, {''r'': -345.75, ''l'': 93,
    ''t'': 2334.091061}, {''r'': -404.5, ''l'': 53, ''t'': 2347.303597}, {''r'': -772.0,
    ''l'': 158, ''t'': 2385.835657}, {''r'': -479.25, ''l'': 75, ''t'': 2405.17525},
    {''r'': -293.5, ''l'': 79, ''t'': 2425.07318}, {''r'': -491.5, ''l'': 79, ''t'':
    2444.702401}, {''r'': -548.0, ''l'': 95, ''t'': 2468.739766}, {''r'': -558.0,
    ''l'': 97, ''t'': 13.43086}, {''r'': -452.0, ''l'': 67, ''t'': 21.959301}, {''r'':
    -420.75, ''l'': 58, ''t'': 29.980798}, {''r'': -657.75, ''l'': 125, ''t'': 45.31281},
    {''r'': -558.0, ''l'': 97, ''t'': 13.885772}, {''r'': -452.0, ''l'': 67, ''t'':
    22.448069}, {''r'': -420.75, ''l'': 58, ''t'': 29.943794}, {''r'': -657.75, ''l'':
    125, ''t'': 45.683267}, {''r'': -557.0, ''l'': 97, ''t'': 13.487342}, {''r'':
    -452.0, ''l'': 67, ''t'': 22.205085}, {''r'': -420.75, ''l'': 58, ''t'': 30.014709},
    {''r'': -657.75, ''l'': 125, ''t'': 45.414211}, {''r'': -558.0, ''l'': 97, ''t'':
    14.430147}, {''r'': -449.0, ''l'': 66, ''t'': 22.71562}, {''r'': -422.75, ''l'':
    59, ''t'': 30.237716}, {''r'': -657.75, ''l'': 125, ''t'': 44.838189}, {''r'':
    -455.0, ''l'': 68, ''t'': 53.073402}, {''r'': -473.25, ''l'': 73, ''t'': 61.911526},
    {''r'': -233.0, ''l'': 62, ''t'': 69.670496}, {''r'': -520.5, ''l'': 86, ''t'':
    79.966942}, {''r'': -435.75, ''l'': 62, ''t'': 87.764227}, {''r'': -549.0, ''l'':
    95, ''t'': 99.20472}, {''r'': -601.5, ''l'': 110, ''t'': 112.252268}, {''r'':
    -612.5, ''l'': 113, ''t'': 126.072629}, {''r'': -493.25, ''l'': 78, ''t'': 135.693128},
    {''r'': -479.25, ''l'': 75, ''t'': 144.905106}, {''r'': -596.25, ''l'': 108, ''t'':
    158.318609}, {''r'': -722.5, ''l'': 144, ''t'': 175.526664}, {''r'': -745.75,
    ''l'': 151, ''t'': 193.325797}, {''r'': -261.0, ''l'': 69, ''t'': 202.514148},
    {''r'': -495.5, ''l'': 80, ''t'': 212.338647}, {''r'': -685.25, ''l'': 134, ''t'':
    228.6161}, {''r'': -317.5, ''l'': 85, ''t'': 239.601024}, {''r'': -313.5, ''l'':
    84, ''t'': 250.767375}, {''r'': -465.25, ''l'': 71, ''t'': 259.646036}, {''r'':
    -512.5, ''l'': 84, ''t'': 269.904078}, {''r'': -457.0, ''l'': 68, ''t'': 278.649775},
    {''r'': -472.25, ''l'': 73, ''t'': 287.786835}, {''r'': -362.0, ''l'': 98, ''t'':
    299.944605}, {''r'': -443.0, ''l'': 65, ''t'': 307.750744}, {''r'': -496.5, ''l'':
    80, ''t'': 318.143352}, {''r'': -499.5, ''l'': 81, ''t'': 328.408042}, {''r'':
    -608.5, ''l'': 112, ''t'': 341.712344}, {''r'': -293.5, ''l'': 79, ''t'': 351.558433},
    {''r'': -528.75, ''l'': 89, ''t'': 362.562478}, {''r'': -568.0, ''l'': 100, ''t'':
    374.519396}, {''r'': -505.5, ''l'': 82, ''t'': 384.413339}, {''r'': -512.5, ''l'':
    84, ''t'': 394.998682}, {''r'': -23472.0, ''l'': 126, ''t'': 15.790066}, {''r'':
    -21336.75, ''l'': 87, ''t'': 26.109949}, {''r'': -60195.0, ''l'': 160, ''t'':
    45.071702}, {''r'': -20929.5, ''l'': 142, ''t'': 63.510865}, {''r'': -91810.75,
    ''l'': 213, ''t'': 90.205258}, {''r'': -22601.5, ''l'': 106, ''t'': 103.50532},
    {''r'': -20678.25, ''l'': 128, ''t'': 120.080268}, {''r'': -22637.75, ''l'': 116,
    ''t'': 134.184319}, {''r'': -20730.75, ''l'': 86, ''t'': 144.479672}, {''r'':
    -527.75, ''l'': 89, ''t'': 13.832279}, {''r'': -285.25, ''l'': 76, ''t'': 25.208571},
    {''r'': -418.75, ''l'': 58, ''t'': 34.048878}, {''r'': -450.75, ''l'': 123, ''t'':
    51.696409}, {''r'': -461.0, ''l'': 69, ''t'': 62.913867}, {''r'': -473.25, ''l'':
    73, ''t'': 72.640665}, {''r'': -233.0, ''l'': 62, ''t'': 80.465961}, {''r'': -520.5,
    ''l'': 86, ''t'': 90.865942}, {''r'': -435.75, ''l'': 62, ''t'': 98.73864}, {''r'':
    -350.0, ''l'': 95, ''t'': 110.300616}, {''r'': -396.5, ''l'': 51, ''t'': 22.116698},
    {''r'': -418.75, ''l'': 58, ''t'': 40.954063}, {''r'': -459.0, ''l'': 69, ''t'':
    61.406471}, {''r'': -415.75, ''l'': 57, ''t'': 80.072975}, {''r'': -523.5, ''l'':
    87, ''t'': 101.523725}], maxlen=100)'
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 1.0e-05
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x00000218A21BCDC8>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 1
n_epochs:
  desc: null
  value: 10
n_steps:
  desc: null
  value: 8192
normalize_advantage:
  desc: null
  value: 'True'
num_timesteps:
  desc: null
  value: 50674
observation_space:
  desc: null
  value: "Box([[[[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10.\
    \ -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]]\n\n  [[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10.\
    \ -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n \
    \  [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]]\n\n  [[-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   ...\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]\n   [-10. -10. -10. ... -10. -10. -10.]]]\n\n\n [[[-10. -10. -10. ...\
    \ -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]\n   ...\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10.\
    \ -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]]\n\n \
    \ [[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]]\n\n  [[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10.\
    \ -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]]]\n\n\n [[[-10. -10. -10. ... -10. -10. -10.]\n   [-10.\
    \ -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]]\n\n  [[-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   ...\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]\n   [-10. -10. -10. ... -10. -10. -10.]]\n\n  [[-10. -10. -10. ... -10.\
    \ -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10.\
    \ -10. -10.]\n   ...\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]]]\n\n\n [[[-10.\
    \ -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10.\
    \ -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]]\n\
    \n  [[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n\
    \   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10.\
    \ -10.]]\n\n  [[-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10. ... -10.\
    \ -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   ...\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]\n   [-10. -10. -10. ... -10. -10. -10.]\n   [-10. -10. -10.\
    \ ... -10. -10. -10.]]]], [[[[1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1. 1. 1. ... 1. 1. 1.]\n \
    \  [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ...\
    \ 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1.\
    \ 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]]]\n\n\n [[[1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1. 1. 1. ... 1. 1. 1.]\n \
    \  [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ...\
    \ 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1.\
    \ 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]]]\n\n\n [[[1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1. 1. 1. ... 1. 1. 1.]\n \
    \  [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ...\
    \ 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1.\
    \ 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]]]\n\n\n [[[1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1. 1. 1. ... 1. 1. 1.]\n \
    \  [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   ...\n   [1. 1. 1. ...\
    \ 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]]\n\n  [[1.\
    \ 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n\
    \   ...\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1. ... 1. 1. 1.]\n   [1. 1. 1.\
    \ ... 1. 1. 1.]]]], (4, 3, 84, 84), float32)"
policy:
  desc: null
  value: "ActorCriticCnnPolicy(\n  (features_extractor): Atari_PPO_Adapted_CNN(\n\
    \    (network): Sequential(\n      (0): Conv2d(12, 32, kernel_size=(8, 8), stride=(4,\
    \ 4))\n      (1): ReLU()\n      (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2,\
    \ 2))\n      (3): ReLU()\n      (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1,\
    \ 1))\n      (5): ReLU()\n      (6): Flatten(start_dim=1, end_dim=-1)\n      (7):\
    \ Linear(in_features=3136, out_features=256, bias=True)\n    )\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (shared_net): Sequential()\n    (policy_net): Sequential(\n\
    \      (0): Linear(in_features=256, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n    (value_net): Sequential(\n      (0): Linear(in_features=256, out_features=64,\
    \ bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (3): Tanh()\n    )\n  )\n  (action_net): Linear(in_features=64,\
    \ out_features=12, bias=True)\n  (value_net): Linear(in_features=64, out_features=1,\
    \ bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticCnnPolicy'>
policy_kwargs:
  desc: null
  value: '{''features_extractor_class'': <class ''ppo_util.Atari_PPO_Adapted_CNN''>,
    ''features_extractor_kwargs'': {''features_dim'': 256}}'
policy_type:
  desc: null
  value: CnnPolicy
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x00000218A221F888>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 1
start_time:
  desc: null
  value: 1651992597.2279975
target_kl:
  desc: null
  value: None
tensorboard_log:
  desc: null
  value: runs/Run 01
training_kwargs:
  desc: null
  value:
    batch_size: 64
    device: cpu
    ent_coef: 0.0
    gamma: 0.99
    learning_rate: 1.0e-05
    n_steps: 8192
    seed: 1
    verbose: 1
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
vf_coef:
  desc: null
  value: 0.5
